# Generated by Django 4.1.7 on 2023-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230907_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
