# Generated by Django 4.1.7 on 2023-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_pricelist_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='comments',
        ),
        migrations.AddField(
            model_name='mjournal',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
