# Generated by Django 4.1.7 on 2023-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_pricelist_comments_mjournal_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjournal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='difference',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='s_totalcre',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='s_totaldeb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='total_cre',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='total_deb',
            field=models.FloatField(default=0.0),
        ),
    ]
