# Generated by Django 4.1.7 on 2023-10-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_man_journal_comment_proj'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
